function showone(){
    document.getElementById("one").style.display=("block");
    document.getElementById("two").style.display=("none");
    document.getElementById("three").style.display=("none");
    document.getElementById("four").style.display=("none");
    document.getElementById("five").style.display=("none");
    document.getElementById("six").style.display=("none");
    document.getElementById("seven").style.display=("none");
    document.getElementById("eight").style.display=("none");
    document.getElementById("nine").style.display=("none");
    document.getElementById("ten").style.display=("none");     
}
function showtwo(){
    document.getElementById("one").style.display=("none");
    document.getElementById("two").style.display=("block");
    document.getElementById("three").style.display=("none");
    document.getElementById("four").style.display=("none");
    document.getElementById("five").style.display=("none");
    document.getElementById("six").style.display=("none");
    document.getElementById("seven").style.display=("none");
    document.getElementById("eight").style.display=("none");
    document.getElementById("nine").style.display=("none");
    document.getElementById("ten").style.display=("none");     
}
function showthree(){
    document.getElementById("one").style.display=("none");
    document.getElementById("two").style.display=("none");
    document.getElementById("three").style.display=("block");
    document.getElementById("four").style.display=("none");
    document.getElementById("five").style.display=("none");
    document.getElementById("six").style.display=("none");
    document.getElementById("seven").style.display=("none");
    document.getElementById("eight").style.display=("none");
    document.getElementById("nine").style.display=("none");
    document.getElementById("ten").style.display=("none");     
}
function showfour(){
    document.getElementById("one").style.display=("none");
    document.getElementById("two").style.display=("none");
    document.getElementById("three").style.display=("none");
    document.getElementById("four").style.display=("block");
    document.getElementById("five").style.display=("none");
    document.getElementById("six").style.display=("none");
    document.getElementById("seven").style.display=("none");
    document.getElementById("eight").style.display=("none");
    document.getElementById("nine").style.display=("none");
    document.getElementById("ten").style.display=("none");     
}
function showfive(){
    document.getElementById("one").style.display=("none");
    document.getElementById("two").style.display=("none");
    document.getElementById("three").style.display=("none");
    document.getElementById("four").style.display=("none");
    document.getElementById("five").style.display=("block");
    document.getElementById("six").style.display=("none");
    document.getElementById("seven").style.display=("none");
    document.getElementById("eight").style.display=("none");
    document.getElementById("nine").style.display=("none");
    document.getElementById("ten").style.display=("none");     
}
function showsix(){
    document.getElementById("one").style.display=("none");
    document.getElementById("two").style.display=("none");
    document.getElementById("three").style.display=("none");
    document.getElementById("four").style.display=("none");
    document.getElementById("five").style.display=("none");
    document.getElementById("six").style.display=("block");
    document.getElementById("seven").style.display=("none");
    document.getElementById("eight").style.display=("none");
    document.getElementById("nine").style.display=("none");
    document.getElementById("ten").style.display=("none");     
}
function showseven(){
    document.getElementById("one").style.display=("none");
    document.getElementById("two").style.display=("none");
    document.getElementById("three").style.display=("none");
    document.getElementById("four").style.display=("none");
    document.getElementById("five").style.display=("none");
    document.getElementById("six").style.display=("none");
    document.getElementById("seven").style.display=("block");
    document.getElementById("eight").style.display=("none");
    document.getElementById("nine").style.display=("none");
    document.getElementById("ten").style.display=("none");     
}
function showeight(){
    document.getElementById("one").style.display=("none");
    document.getElementById("two").style.display=("none");
    document.getElementById("three").style.display=("none");
    document.getElementById("four").style.display=("none");
    document.getElementById("five").style.display=("none");
    document.getElementById("six").style.display=("none");
    document.getElementById("seven").style.display=("none");
    document.getElementById("eight").style.display=("block");
    document.getElementById("nine").style.display=("none");
    document.getElementById("ten").style.display=("none");     
}
function shownine(){
    document.getElementById("one").style.display=("none");
    document.getElementById("two").style.display=("none");
    document.getElementById("three").style.display=("none");
    document.getElementById("four").style.display=("none");
    document.getElementById("five").style.display=("none");
    document.getElementById("six").style.display=("none");
    document.getElementById("seven").style.display=("none");
    document.getElementById("eight").style.display=("none");
    document.getElementById("nine").style.display=("block");
    document.getElementById("ten").style.display=("none");     
}
function showten(){
    document.getElementById("one").style.display=("none");
    document.getElementById("two").style.display=("none");
    document.getElementById("three").style.display=("none");
    document.getElementById("four").style.display=("none");
    document.getElementById("five").style.display=("none");
    document.getElementById("six").style.display=("none");
    document.getElementById("seven").style.display=("none");
    document.getElementById("eight").style.display=("none");
    document.getElementById("nine").style.display=("none");
    document.getElementById("ten").style.display=("block");     
}
